#lang planet neil/sicp
;①
(define (lorna-father)
  (let ((moore 'mary)
        (barnacle 'melissa)
        (downing (amb 'gabrielle 'lorna 'rosalind))
        (hall (amb 'gabrielle 'lorna))
        (parker (amb 'lorna 'rosalind)))
    (require (or (and (equal? downing 'gabrielle) (equal? 'melissa parker))
                 (and (equal? hall 'gabrielle) (equal? 'rosalind parker))))
    (require (distinct? (list downing hall parker)))
    (cond ((equal? 'lorna downing) 'downing)
          ((equal? 'lorna hall) 'hall)
          (else 'parker))))

;②
(define (lorna-father)
  (let ((moore (amb 'mary 'gabrielle 'lorna 'rosalind))
        (barnacle 'melissa)
        (downing (amb 'mary 'gabrielle 'lorna 'rosalind))
        (hall (amb 'mary 'gabrielle 'lorna))
        (parker (amb 'mary 'lorna 'rosalind)))
    (require (or (and (equal? downing 'gabrielle) (equal? 'melissa parker))
                 (and (equal? hall 'gabrielle) (equal? 'rosalind parker))
                 (and (equal? moore 'gabrielle) (equal? 'lorna parker))))
    (require (distinct? (list moore downing hall parker)))
    (cond ((equal? 'lorna moore) 'moore)
          ((equal? 'lorna downing) 'downing)
          ((equal? 'lorna hall) 'hall)
          (else 'parker))))

