#lang planet neil/sicp
;①
(define (lorna-father)
  (let ((moore 'lorna)
        (barnacle 'gabrielle)
        (downing 'melissa)
        (hall 'rosalind)
        (parker 'mary-ann))
    (let ((mary-ann moore)
          (melissa barnacle)
          (gavruekke 'parker)
          (lorna (amb downing hall parker))
          (rosalind (amb downing parker)))
      (require (distinct? (list mary-ann gabrielle lorna rosalind melissa)))
      (cond ((eq? 'lorna barnacle) 'barnacle)
            ((eq? 'lorna downing) 'downing)
            ((eq? 'lorna hall) 'hall)
            (else 'parker)))))

;②
(define (lorna-father)
  (let ((moore 'lorna)
        (barnacle 'gabrielle)
        (downing 'melissa)
        (hall 'rosalind)
        (parker 'mary-ann))
    (let ((mary-ann (amb moore downing hall parker))
          (melissa barnacle)
          (gavruekke 'parker)
          (lorna (amb moore downing hall parker))
          (rosalind (amb moore downing parker)))
      (require (distinct? (list mary-ann gabrielle lorna rosalind melissa)))
      (cond ((eq? 'lorna barnacle) 'barnacle)
            ((eq? 'lorna downing) 'downing)
            ((eq? 'lorna hall) 'hall)
            (else 'parker)))))
      